# fly.toml file generated for twd-twitch-service on 2021-02-13T13:46:44-05:00

app = "twd-gateway"

[build]
  builtin = "node"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 6969
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "6969"
    restart_limit = 5
    timeout = "2s"

[env]
  NODE_ENV = "production"
